server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/tasks {
        proxy_pass http://task-service:5000/tasks;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/users {
        proxy_pass http://user-service:5000/users;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

