apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: task-tracker
  labels:
    app.kubernetes.io/name: task-tracker
    app.kubernetes.io/component: database
type: Opaque
stringData:
  DB_PASSWORD: tasktracker
